"""empty message

Revision ID: 26aae47fbe36
Revises: 88b7c621a278
Create Date: 2022-08-12 18:03:26.775058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26aae47fbe36'
down_revision = '88b7c621a278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.add_column('venues', sa.Column('date_created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'date_created')
    op.drop_column('artists', 'date_created')
    # ### end Alembic commands ###
