"""empty message

Revision ID: 29f595a72bd8
Revises: f703e02d1982
Create Date: 2022-08-10 13:22:13.459322

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f595a72bd8'
down_revision = 'f703e02d1982'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=False))
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=150), nullable=True))
    op.drop_column('artists', 'looking_for_venues')
    op.drop_column('artists', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('description', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
    op.add_column('artists', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_description')
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
